### ISSUE TITLE
question, not an issue

### ISSUE THREAD

**Issue by cottrell** [hmrc/personal-income#57]
Not sure where else to ask this.

Am looking for a tax function that is something like taxes = f(year, income, pension) ... hoping the data and list of assembled functions is somewhere in your tools. Ideally want this for as many years as possible. Interested even if you know if citizens trying to put this together in an open way.

**Comment by Smudgey** [comment]
Hi @cottrell apologies for the much delayed response. Unfortunately there isn't a single function that can simplify the calculation of taxes down to f(year, income, pension) for all scenarios, if thats what you mean? This repo is primarily used by the HMRC Mobile App team, to return some PAYE information for our users as well as some Tax Credits functionality.

Apologies again for the delayed response and that we don't quite have what you are looking for.
